const gotReferenceFrom = [
    { key: 1, referenceFrom: "Doctor" },
    { key: 2, referenceFrom: "Family or Friend" },
    { key: 3, referenceFrom: "Marketing Campaign" },
    { key: 4, referenceFrom: "News Paper" },
    { key: 5, referenceFrom: "Radio" },
    { key: 6, referenceFrom: "Existing Patient" },
    { key: 7, referenceFrom: "Google" },
    { key: 8, referenceFrom: "Government Hospital" },
    { key: 9, referenceFrom: "WebSite" },
    { key: 10, referenceFrom: "Social Media" },
    { key: 11, referenceFrom: "Health Campaign" },
    { key: 12, referenceFrom: "NA" },
]

const callPurpose = [
    { key: 1, purpose: "Appointment" },
    { key: 2, purpose: "Rescheduling of Apppointment" },
    { key: 3, purpose: "Covid Query" },
    { key: 4, purpose: "Genral Query" },
    { key: 5, purpose: "Surgery" },
    { key: 6, purpose: "Health Checkup" },
    { key: 7, purpose: "Emergency Query" },
    { key: 8, purpose: "Internal to Internal Transer" },
    { key: 9, purpose: "Internal to External Transfer" },
    { key: 10, purpose: "External to Internal Transfer" },
    { key: 11, purpose: "External to External Transfer" },
    { key: 12, purpose: "Call Drop" },
    { key: 13, purpose: "marketing Campaign" },
    { key: 14, purpose: "Complaints" },
    { key: 15, purpose: "Other" },
    { key: 16, purpose: "OPD Timings" },
    { key: 17, purpose: "Diagnose or Test Price" },
    { key: 18, purpose: "Reports" },
    { key: 19, purpose: "Govt Health Schemes" },
    { key: 20, purpose: "Not Govenment Scheme" },
    { key: 21, purpose: "billing" },
    { key: 22, purpose: "IPD Transfers" },
    { key: 23, purpose: "Nursing" },
    { key: 24, purpose: "Pharmacy" },
    { key: 25, purpose: "Ambulance" },
];


const departments = [
    { key: 1, department: "Reception" },
    { key: 2, department: "Canteen" },
    { key: 3, department: "Diatician" },
    { key: 4, department: "IPD Billing" },
    { key: 5, department: "IPD Pharmacy" },
    { key: 6, department: "HR" },
    { key: 7, department: "MRD" },
    { key: 8, department: "Physiotheraphy" },
    { key: 9, department: "Marketing" },
    { key: 10, department: "IT" },
    { key: 11, department: "LAB" },
    { key: 12, department: "Emergency" },
    { key: 13, department: "OPD Pharmacy" },
    { key: 14, department: "TPA" },
    { key: 15, department: "Cath Lab" },
    { key: 16, department: "OT Counter" },
    { key: 17, department: "Labour Room" },
    { key: 18, department: "NICU" },
    { key: 19, department: "CTVS ICU" },
    { key: 20, department: "Dialasis Room" },
    { key: 21, department: "ICU" },
    { key: 22, department: "Accounts/Billing" },
    { key: 23, department: "Administration" },
    { key: 24, department: "Maintenance/Store" },
    { key: 25, department: "Neurology" },
    { key: 26, department: "Obstetrics & Gynecology" },
    { key: 27, department: "General and Laproscopic Surgery" },
    { key: 28, department: "Urology" },
    { key: 29, department: "Pulmonolgy" },
    { key: 20, department: "Orthopedics" },
    { key: 32, department: "Nephrology" },
    { key: 33, department: "Dermatologist" },
    { key: 34, department: "Ent" },
    { key: 35, department: "General Physician" },
    { key: 36, department: "Pediatric" },
    { key: 37, department: "Cardiology" },
    { key: 38, department: "Gereral Ward Female" },
    { key: 39, department: "Radiology" },
    { key: 30, department: "Plastic Surgery" },
    { key: 41, department: "Endocrinolgy" },
    { key: 42, department: "Gestroenterology" },
    { key: 43, department: "Oncology" }
]

const Doctors = [
    { key: 1, doctorName: "Doctor A" },
    { key: 2, doctorName: "Doctor B" },
    { key: 3, doctorName: "Doctor C" },
    { key: 4, doctorName: "Doctor D" },
    { key: 5, doctorName: "Doctor E" },
    { key: 6, doctorName: "Doctor F" },
    { key: 7, doctorName: "Doctor G" },
    { key: 8, doctorName: "Doctor H" },
    { key: 9, doctorName: "Doctor I" },
    { key: 10, doctorName: "Doctor J" },
    { key: 11, doctorName: "Doctor K" },
]

export { callPurpose, gotReferenceFrom, departments, Doctors }