import React from 'react';
import "./Executive.css";


// Simple text icons with clean styling
const iconStyle = {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '24px',
    marginRight: '8px',
    fontSize: '18px',
    color: '#4a4a4a'
};

const EyeIcon = () => <span style={iconStyle}>👁️</span>;
const ClockIcon = () => <span style={iconStyle}>⏱️</span>;
const DownloadIcon = () => <span style={iconStyle}>⬇️</span>;
const SearchIcon = () => <span style={iconStyle}>🔍</span>;

const Reports = () => {
    const reportData = [
        { id: '#RPT-0012', type: 'Daily Call Summary', date: 'Oct 10, 2023', generatedBy: 'System', status: 'completed', actionText: 'View', actionIcon: <EyeIcon />, disabled: false },
        { id: '#RPT-0011', type: 'Weekly Performance', date: 'Oct 3-9, 2023', generatedBy: 'Sarah Johnson', status: 'completed', actionText: 'View', actionIcon: <EyeIcon />, disabled: false },
        { id: '#RPT-0010', type: 'Call Duration Analysis', date: 'Sep 2023', generatedBy: 'System', status: 'completed', actionText: 'View', actionIcon: <EyeIcon />, disabled: false },
        { id: '#RPT-0009', type: 'Appointment Analysis', date: 'Q3 2023', generatedBy: 'Michael Brown', status: 'pending', actionText: 'Processing', actionIcon: <ClockIcon />, disabled: true },
    ];

    return (
        <div className="page" id="reports">
            <div className="page-header">
                <h2>Detailed Reports</h2>
                <div>
                    <button className="btn"><DownloadIcon /> Export</button>
                </div>
            </div>

            <div className="search-box">
                <input style={{ height: "30px", width: "210px", borderRadius:"4px"}} type="text" placeholder="Search reports..." />
                <button style={{ borderRadius:"4px", border:"none",}} ><SearchIcon /></button>
            </div>

            <div className="table-container">
                <table style={{
                    width: "100%", textAlign: "center", paddingLeft: "70px",
                    paddingTop: "31px", alignItems: "center"
                }} >
                    <thead>
                        <tr>
                            <th>Report ID</th>
                            <th>Report Type</th>
                            <th>Date Range</th>
                            <th>Generated By</th>
                            <th>Status</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {reportData.map(report => (
                            <tr key={report.id}>
                                <td>{report.id}</td>
                                <td>{report.type}</td>
                                <td>{report.date}</td>
                                <td>{report.generatedBy}</td>
                                <td><span className={`status ${report.status}`}>{report.status.charAt(0).toUpperCase() + report.status.slice(1)}</span></td>
                                <td>
                                    <button className="btn btn-secondary" disabled={report.disabled}>
                                        {report.actionIcon} {report.actionText}
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Reports;