export const dummyWhatsappConversations = [
    {
        id: 1,
        patient: {
            name: "Rahul Sharma",
            mobile: "+91 98765 43210",
            uhid: "UHID-10234",
            age: 41,
            gender: "Male",
            bloodGroup: "O+",
            email: "rahul.sharma@email.com",
            hospital: "Jindal Hospital",
            branch: "Noida",
            department: "Cardiology",
            doctor: "Dr. Neha Kapoor",
            lastVisit: "2026-07-10",
            upcomingAppointment: "2026-08-02",
            totalAppointments: 6,
            pendingBills: "₹12,450",
            medicalNotes: "History of hypertension and mild arrhythmia. Reassess after 2 weeks.",
            medications: ["Amlodipine 5mg", "Metoprolol 50mg"],
        },
        hospital: "Jindal Hospital",
        branch: "Noida",
        department: "Cardiology",
        doctor: "Dr. Neha Kapoor",
        status: "Bot Handling",
        lastMessage: "Please choose your preferred department for appointment follow-up.",
        lastMessageTime: "09:18",
        unreadCount: 2,
        messages: [
            { id: 1, sender: "bot", text: "Hello Rahul! I’m your hospital assistant. How can I help today?", timestamp: "09:02" },
            { id: 2, sender: "patient", text: "I need help with my appointment follow-up.", timestamp: "09:03" },
            { id: 3, sender: "bot", type: "options", options: ["Book Appointment", "Check Lab Report", "Talk to Human"], timestamp: "09:04" },
            { id: 4, sender: "bot", type: "card", title: "Department Selection", description: "Choose the right care team for your concern.", timestamp: "09:05" },
            { id: 5, sender: "system", text: "Transferred to the Cardiology team", timestamp: "09:10" },
        ],
    },
    {
        id: 2,
        patient: {
            name: "Priya Verma",
            mobile: "+91 99887 55667",
            uhid: "UHID-10981",
            age: 32,
            gender: "Female",
            bloodGroup: "AB+",
            email: "priya.verma@email.com",
            hospital: "Jindal Hospital",
            branch: "Gurugram",
            department: "Dermatology",
            doctor: "Dr. Ankit Rao",
            lastVisit: "2026-06-28",
            upcomingAppointment: "2026-07-31",
            totalAppointments: 4,
            pendingBills: "₹7,100",
            medicalNotes: "Allergic to penicillin. Needs monthly skin checkups.",
            medications: ["Cetirizine 10mg", "Hydrocortisone cream"],
        },
        hospital: "Jindal Hospital",
        branch: "Gurugram",
        department: "Dermatology",
        doctor: "Dr. Ankit Rao",
        status: "Human Handling",
        lastMessage: "I’ve shared the prescription PDF for you to review.",
        lastMessageTime: "08:44",
        unreadCount: 1,
        messages: [
            { id: 1, sender: "bot", text: "Hello Priya, I can help you with prescription support.", timestamp: "08:25" },
            { id: 2, sender: "patient", text: "I need my latest prescription again.", timestamp: "08:27" },
            { id: 3, sender: "executive", text: "I’ve attached the latest prescription for your records.", timestamp: "08:31" },
            { id: 4, sender: "patient", type: "pdf", caption: "Prescription_2026.pdf", timestamp: "08:33" },
            { id: 5, sender: "executive", type: "audio", caption: "Audio message", timestamp: "08:38" },
        ],
    },
    {
        id: 3,
        patient: {
            name: "Rohit Jain",
            mobile: "+91 91234 56789",
            uhid: "UHID-12045",
            age: 29,
            gender: "Male",
            bloodGroup: "A-",
            email: "rohit.jain@email.com",
            hospital: "Jindal Hospital",
            branch: "Faridabad",
            department: "Orthopedics",
            doctor: "Dr. Meera Bhatia",
            lastVisit: "2026-05-16",
            upcomingAppointment: "2026-08-05",
            totalAppointments: 3,
            pendingBills: "₹3,250",
            medicalNotes: "Post-op follow-up scheduled for next week.",
            medications: ["Ibuprofen 400mg", "Calcium supplement"],
        },
        hospital: "Jindal Hospital",
        branch: "Faridabad",
        department: "Orthopedics",
        doctor: "Dr. Meera Bhatia",
        status: "Closed",
        lastMessage: "The appointment was confirmed successfully.",
        lastMessageTime: "Yesterday",
        unreadCount: 0,
        messages: [
            { id: 1, sender: "bot", text: "Hi Rohit, I can confirm your follow-up visit.", timestamp: "Yesterday 18:20" },
            { id: 2, sender: "patient", text: "Please confirm it for tomorrow morning.", timestamp: "Yesterday 18:22" },
            { id: 3, sender: "bot", type: "card", title: "Appointment Confirmed", description: "Your slot is booked for 10:30 AM tomorrow.", timestamp: "Yesterday 18:24" },
            { id: 4, sender: "executive", text: "Please arrive 15 minutes early for registration.", timestamp: "Yesterday 18:26" },
            { id: 5, sender: "system", text: "Conversation closed successfully", timestamp: "Yesterday 18:27" },
        ],
    },
];

export const conversationStats = [
    { label: "Total Conversations", value: "1,248", icon: "Forum", color: "primary" },
    { label: "Active Chats", value: "186", icon: "Chat", color: "success" },
    { label: "Waiting for Human", value: "34", icon: "SupportAgent", color: "warning" },
    { label: "Bot Resolution Rate", value: "91%", icon: "AutoAwesome", color: "secondary" },
];

export const filterOptions = {
    hospitals: ["All Hospitals", "Jindal Hospital", "Fortis", "Apollo"],
    branches: ["All Branches", "Noida", "Gurugram", "Faridabad"],
    departments: ["All Departments", "Cardiology", "Dermatology", "Orthopedics", "Neurology"],
    doctors: ["All Doctors", "Dr. Neha Kapoor", "Dr. Ankit Rao", "Dr. Meera Bhatia", "Dr. Raghav Sharma"],
    statuses: ["All Status", "Active", "Closed", "Bot Handling", "Human Handling"],
    executives: ["All Executives", "Aarav Singh", "Nisha Patel", "Karan Desai"],
    messageTypes: ["All Types", "Text", "Image", "PDF", "Audio"],
};
