export const dummyFlows = [
    {
        id: "flow-appointment",
        name: "Appointment Booking",
        hospitalName: "Jindal Hospital",
        branch: "Cardiology",
        status: "Published",
        version: 3.2,
        lastUpdated: "2026-07-28",
        createdBy: "Asha Verma",
        totalNodes: 12,
        publishStatus: "Live",
        hospital: "Jindal Hospital",
        nodes: [
            {
                id: "start-1",
                name: "Start",
                type: "Start Node",
                messageContent: "Patient journey begins.",
                headerText: "Welcome",
                footerText: "Tap to proceed",
                dynamicVariables: "{patientName}",
                quickReplies: ["Book Appointment", "Know OPD Timings"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 30,
                httpMethod: "POST",
                apiUrl: "https://api.example.com/appointment",
                jsonPayload: '{"patient": "{patientName}", "branch": "Cardiology"}',
                variableMapping: "patientName -> name",
                errorHandling: "Retry once with fallback",
                successPath: "Appointment Confirmed",
                failurePath: "Human Hand-off",
                notes: "Collects intent for appointment flow.",
                position: { x: 40, y: 80 },
                nextNodeId: "welcome-2"
            },
            {
                id: "welcome-2",
                name: "Welcome Message",
                type: "Welcome Message",
                messageContent: "Hello {patientName}, how can we assist you today?",
                headerText: "Hello",
                footerText: "Select one option",
                dynamicVariables: "{patientName}",
                quickReplies: ["Book Appointment", "Lab Reports", "Billing"],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Show fallback message",
                successPath: "Department Selection",
                failurePath: "Retry",
                notes: "Greets the patient and offers options.",
                position: { x: 280, y: 80 },
                nextNodeId: "department-3"
            },
            {
                id: "department-3",
                name: "Department Selection",
                type: "Department Selection",
                messageContent: "Please choose the department you need.",
                headerText: "Department",
                footerText: "Choose a department",
                dynamicVariables: "",
                quickReplies: ["Cardiology", "Orthopedics", "Neurology"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "dept -> selectedDepartment",
                errorHandling: "Ask again",
                successPath: "Doctor Selection",
                failurePath: "Retry",
                notes: "Routes to proper specialist.",
                position: { x: 520, y: 80 },
                nextNodeId: "doctor-4"
            },
            {
                id: "doctor-4",
                name: "Doctor Selection",
                type: "Doctor Selection",
                messageContent: "Choose a doctor for your consultation.",
                headerText: "Doctor",
                footerText: "Available today",
                dynamicVariables: "",
                quickReplies: ["Dr. Rao", "Dr. Nair"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "doctorId -> doctor",
                errorHandling: "Show nearest slot",
                successPath: "Date Selection",
                failurePath: "Retry",
                notes: "Helps patient select a doctor.",
                position: { x: 760, y: 80 },
                nextNodeId: "date-5"
            },
            {
                id: "date-5",
                name: "Date Selection",
                type: "Date Selection",
                messageContent: "Select your preferred appointment date.",
                headerText: "Date",
                footerText: "Choose your date",
                dynamicVariables: "",
                quickReplies: ["Today", "Tomorrow", "Next Week"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "selectedDate -> slotDate",
                errorHandling: "Prompt with calendar",
                successPath: "Time Slot Selection",
                failurePath: "Retry",
                notes: "Captures appointment date.",
                position: { x: 1000, y: 80 },
                nextNodeId: "time-6"
            },
            {
                id: "time-6",
                name: "Time Slot Selection",
                type: "Time Slot Selection",
                messageContent: "Choose a convenient time slot.",
                headerText: "Time",
                footerText: "Slots are updated in real time",
                dynamicVariables: "",
                quickReplies: ["09:00", "11:30", "15:00"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 20,
                httpMethod: "POST",
                apiUrl: "https://api.example.com/slots",
                jsonPayload: '{"date": "{selectedDate}"}',
                variableMapping: "slot -> selectedSlot",
                errorHandling: "Show available alternatives",
                successPath: "End Conversation",
                failurePath: "Retry",
                notes: "Captures preferred visit slot.",
                position: { x: 1240, y: 80 },
                nextNodeId: "end-7"
            },
            {
                id: "end-7",
                name: "End Conversation",
                type: "End Conversation",
                messageContent: "Your appointment request has been received. We will confirm shortly.",
                headerText: "Confirmed",
                footerText: "Thank you",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends the successful journey.",
                position: { x: 1480, y: 80 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 0,
            missingEndNodes: 0,
            invalidConfigurations: 1
        },
        analytics: {
            totalExecutions: 1824,
            successRate: 94,
            humanHandoverRate: 8,
            averageCompletionTime: "3m 12s",
            dropOffRate: 6,
            mostClickedButtons: ["Book Appointment", "Confirm Slot"]
        },
        versions: [
            { version: 3.2, updatedAt: "Today, 09:15", note: "Added confirmation card" },
            { version: 3.1, updatedAt: "Yesterday, 18:42", note: "Improved doctor selection" },
            { version: 3.0, updatedAt: "Jul 24, 2026", note: "Published to live hospitals" }
        ],
        recentActivity: [
            { id: 1, title: "Published flow to Jindal Hospital", time: "10 min ago" },
            { id: 2, title: "Updated appointment confirmation message", time: "1 hr ago" },
            { id: 3, title: "Added dynamic patient variables", time: "2 hrs ago" }
        ],
        preview: {
            title: "Appointment Booking",
            messages: [
                { type: "bot", text: "Hello Priya, how can we assist you today?" },
                { type: "user", text: "Book appointment" },
                { type: "bot", text: "Choose a department", options: ["Cardiology", "Orthopedics"] },
                { type: "bot", text: "Dr. Rao is available today at 11:30", card: true }
            ]
        }
    },
    {
        id: "flow-opd",
        name: "OPD Information",
        hospitalName: "Metro Care Hospital",
        branch: "General OPD",
        status: "Draft",
        version: 2.1,
        lastUpdated: "2026-07-24",
        createdBy: "Rahul Mehta",
        totalNodes: 9,
        publishStatus: "Draft",
        hospital: "Metro Care Hospital",
        nodes: [
            {
                id: "opd-start",
                name: "Start",
                type: "Start Node",
                messageContent: "Start OPD information flow",
                headerText: "Welcome",
                footerText: "Tap to start",
                dynamicVariables: "{hospitalName}",
                quickReplies: ["OPD Timings", "Doctor Availability"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 1,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Fallback",
                successPath: "Welcome Message",
                failurePath: "Retry",
                notes: "Starts the OPD details journey.",
                position: { x: 60, y: 110 },
                nextNodeId: "opd-welcome"
            },
            {
                id: "opd-welcome",
                name: "Welcome Message",
                type: "Welcome Message",
                messageContent: "Welcome to OPD support. We can share timings and departments.",
                headerText: "OPD Support",
                footerText: "Select an option",
                dynamicVariables: "",
                quickReplies: ["Timings", "Departments"],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Show message",
                successPath: "End Node",
                failurePath: "Retry",
                notes: "Supports the OPD information journey.",
                position: { x: 320, y: 110 },
                nextNodeId: "opd-end"
            },
            {
                id: "opd-end",
                name: "End Node",
                type: "End Node",
                messageContent: "Thank you for contacting OPD support.",
                headerText: "Done",
                footerText: "Closing",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends the flow gracefully.",
                position: { x: 580, y: 110 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 1,
            missingEndNodes: 0,
            invalidConfigurations: 0
        },
        analytics: {
            totalExecutions: 632,
            successRate: 89,
            humanHandoverRate: 5,
            averageCompletionTime: "2m 40s",
            dropOffRate: 11,
            mostClickedButtons: ["OPD Timings", "Doctor Availability"]
        },
        versions: [
            { version: 2.1, updatedAt: "Yesterday, 16:20", note: "Updated timing text" },
            { version: 2.0, updatedAt: "Jul 22, 2026", note: "Introduced quick reply options" }
        ],
        recentActivity: [
            { id: 1, title: "Saved draft after content update", time: "3 hrs ago" },
            { id: 2, title: "Added OPD timing quick replies", time: "1 day ago" }
        ],
        preview: {
            title: "OPD Information",
            messages: [
                { type: "bot", text: "Welcome to OPD support. We can share timings and departments." },
                { type: "user", text: "Show timings" },
                { type: "bot", text: "OPD is open from 8:00 AM to 8:00 PM" }
            ]
        }
    },
    {
        id: "flow-billing",
        name: "Billing Support",
        hospitalName: "Saraswati Hospital",
        branch: "Billing Desk",
        status: "Archived",
        version: 1.8,
        lastUpdated: "2026-06-18",
        createdBy: "Nisha Patel",
        totalNodes: 10,
        publishStatus: "Archived",
        hospital: "Saraswati Hospital",
        nodes: [
            {
                id: "bill-start",
                name: "Start",
                type: "Start Node",
                messageContent: "Begin billing assistance",
                headerText: "Help",
                footerText: "We can assist",
                dynamicVariables: "{patientName}",
                quickReplies: ["Invoice", "Payment Receipt"],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Fallback",
                successPath: "Ask Question",
                failurePath: "Retry",
                notes: "Initiates billing support.",
                position: { x: 70, y: 120 },
                nextNodeId: "bill-question"
            },
            {
                id: "bill-question",
                name: "Ask Question",
                type: "Ask Question",
                messageContent: "Do you need a statement or invoice copy?",
                headerText: "Billing",
                footerText: "Choose one",
                dynamicVariables: "",
                quickReplies: ["Statement", "Invoice"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Re-prompt",
                successPath: "End Node",
                failurePath: "Retry",
                notes: "Collects billing intent.",
                position: { x: 340, y: 120 },
                nextNodeId: "bill-end"
            },
            {
                id: "bill-end",
                name: "End Node",
                type: "End Node",
                messageContent: "We will send the requested billing document shortly.",
                headerText: "Thanks",
                footerText: "Support complete",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends the billing flow.",
                position: { x: 610, y: 120 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 0,
            missingEndNodes: 0,
            invalidConfigurations: 2
        },
        analytics: {
            totalExecutions: 481,
            successRate: 82,
            humanHandoverRate: 12,
            averageCompletionTime: "4m 05s",
            dropOffRate: 14,
            mostClickedButtons: ["Invoice", "Payment Receipt"]
        },
        versions: [
            { version: 1.8, updatedAt: "Jun 18, 2026", note: "Archived by operations" },
            { version: 1.7, updatedAt: "Jun 10, 2026", note: "Improved payment receipts" }
        ],
        recentActivity: [
            { id: 1, title: "Archived after workflow review", time: "2 days ago" },
            { id: 2, title: "Updated success path text", time: "4 days ago" }
        ],
        preview: {
            title: "Billing Support",
            messages: [
                { type: "bot", text: "Need help with billing?" },
                { type: "user", text: "Invoice copy" },
                { type: "bot", text: "We will send the invoice to your number shortly" }
            ]
        }
    },
    {
        id: "flow-emergency",
        name: "Emergency Help",
        hospitalName: "Apex Medical Center",
        branch: "Emergency",
        status: "Published",
        version: 4.0,
        lastUpdated: "2026-07-29",
        createdBy: "Kavya Iyer",
        totalNodes: 14,
        publishStatus: "Live",
        hospital: "Apex Medical Center",
        nodes: [
            {
                id: "emg-start",
                name: "Start",
                type: "Start Node",
                messageContent: "Emergency help initiated",
                headerText: "Urgent",
                footerText: "We are here",
                dynamicVariables: "{patientName}",
                quickReplies: ["Call Now", "Share Location"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 3,
                timeoutSeconds: 25,
                httpMethod: "POST",
                apiUrl: "https://api.example.com/emergency",
                jsonPayload: '{"priority": "high"}',
                variableMapping: "location -> emergencyLocation",
                errorHandling: "Escalate to human handover",
                successPath: "Human Handover",
                failurePath: "Retry",
                notes: "Designed for urgent response.",
                position: { x: 60, y: 90 },
                nextNodeId: "emg-handover"
            },
            {
                id: "emg-handover",
                name: "Human Handover",
                type: "Human Handover",
                messageContent: "An agent will contact you immediately.",
                headerText: "Agent Connect",
                footerText: "Please stay available",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Required",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Escalate",
                successPath: "End Node",
                failurePath: "Retry",
                notes: "Transfers to emergency staff.",
                position: { x: 360, y: 90 },
                nextNodeId: "emg-end"
            },
            {
                id: "emg-end",
                name: "End Node",
                type: "End Node",
                messageContent: "We have connected your case to the emergency team.",
                headerText: "Connected",
                footerText: "Thank you",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends urgent flow.",
                position: { x: 660, y: 90 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 0,
            missingEndNodes: 0,
            invalidConfigurations: 0
        },
        analytics: {
            totalExecutions: 312,
            successRate: 97,
            humanHandoverRate: 18,
            averageCompletionTime: "1m 18s",
            dropOffRate: 3,
            mostClickedButtons: ["Call Now", "Share Location"]
        },
        versions: [
            { version: 4.0, updatedAt: "Today, 07:50", note: "Live emergency handover logic" },
            { version: 3.9, updatedAt: "Jul 27, 2026", note: "Improved urgent fallback" }
        ],
        recentActivity: [
            { id: 1, title: "Emergency flow published for Apex Medical", time: "15 min ago" },
            { id: 2, title: "Added location capture step", time: "5 hrs ago" }
        ],
        preview: {
            title: "Emergency Help",
            messages: [
                { type: "bot", text: "Need urgent help?" },
                { type: "user", text: "Call now" },
                { type: "bot", text: "An emergency agent will contact you immediately" }
            ]
        }
    },
    {
        id: "flow-lab",
        name: "Lab Reports",
        hospitalName: "CarePoint Hospital",
        branch: "Diagnostics",
        status: "Draft",
        version: 2.4,
        lastUpdated: "2026-07-20",
        createdBy: "Deepak Sen",
        totalNodes: 11,
        publishStatus: "Draft",
        hospital: "CarePoint Hospital",
        nodes: [
            {
                id: "lab-start",
                name: "Start",
                type: "Start Node",
                messageContent: "Start lab report assistance",
                headerText: "Reports",
                footerText: "We can help",
                dynamicVariables: "{patientName}",
                quickReplies: ["View Report", "Download PDF"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 1,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Fallback",
                successPath: "PDF",
                failurePath: "Retry",
                notes: "Initiates lab report journey.",
                position: { x: 70, y: 100 },
                nextNodeId: "lab-pdf"
            },
            {
                id: "lab-pdf",
                name: "PDF",
                type: "PDF",
                messageContent: "Your report PDF is ready to view.",
                headerText: "Lab Report",
                footerText: "Open the file",
                dynamicVariables: "",
                quickReplies: ["Open PDF", "Share by SMS"],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Show fallback",
                successPath: "End Node",
                failurePath: "Retry",
                notes: "Delivers the report document.",
                position: { x: 340, y: 100 },
                nextNodeId: "lab-end"
            },
            {
                id: "lab-end",
                name: "End Node",
                type: "End Node",
                messageContent: "Thank you for using lab support.",
                headerText: "Done",
                footerText: "Support complete",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends report flow.",
                position: { x: 610, y: 100 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 0,
            missingEndNodes: 0,
            invalidConfigurations: 1
        },
        analytics: {
            totalExecutions: 924,
            successRate: 91,
            humanHandoverRate: 4,
            averageCompletionTime: "2m 50s",
            dropOffRate: 8,
            mostClickedButtons: ["View Report", "Download PDF"]
        },
        versions: [
            { version: 2.4, updatedAt: "Jul 20, 2026", note: "Added PDF delivery option" },
            { version: 2.3, updatedAt: "Jul 15, 2026", note: "Improved wording" }
        ],
        recentActivity: [
            { id: 1, title: "Added PDF support path", time: "Yesterday" },
            { id: 2, title: "Updated diagnostic quick replies", time: "2 days ago" }
        ],
        preview: {
            title: "Lab Reports",
            messages: [
                { type: "bot", text: "Would you like to view your latest lab report?" },
                { type: "user", text: "Open PDF" },
                { type: "bot", text: "Your report is ready" }
            ]
        }
    },
    {
        id: "flow-inquiry",
        name: "General Inquiry",
        hospitalName: "NorthStar Hospital",
        branch: "Front Desk",
        status: "Published",
        version: 2.9,
        lastUpdated: "2026-07-26",
        createdBy: "Mina Joseph",
        totalNodes: 13,
        publishStatus: "Live",
        hospital: "NorthStar Hospital",
        nodes: [
            {
                id: "inq-start",
                name: "Start",
                type: "Start Node",
                messageContent: "General inquiry started",
                headerText: "Hi there",
                footerText: "How can we help?",
                dynamicVariables: "{patientName}",
                quickReplies: ["General Info", "Contact Us"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 1,
                timeoutSeconds: 15,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Fallback",
                successPath: "Text Message",
                failurePath: "Retry",
                notes: "Starts general inquiry path.",
                position: { x: 60, y: 110 },
                nextNodeId: "inq-text"
            },
            {
                id: "inq-text",
                name: "Text Message",
                type: "Text Message",
                messageContent: "How may I assist you with your inquiry today?",
                headerText: "Inquiry",
                footerText: "Please reply",
                dynamicVariables: "",
                quickReplies: ["Contact Desk", "Share Feedback"],
                listOptions: [],
                validationRules: "Required",
                retryCount: 2,
                timeoutSeconds: 20,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "Show fallback",
                successPath: "End Node",
                failurePath: "Retry",
                notes: "Collects user inquiry details.",
                position: { x: 330, y: 110 },
                nextNodeId: "inq-end"
            },
            {
                id: "inq-end",
                name: "End Node",
                type: "End Node",
                messageContent: "We have logged your inquiry. A support agent will assist soon.",
                headerText: "Thanks",
                footerText: "Support complete",
                dynamicVariables: "",
                quickReplies: [],
                listOptions: [],
                validationRules: "Optional",
                retryCount: 0,
                timeoutSeconds: 10,
                httpMethod: "GET",
                apiUrl: "",
                jsonPayload: "{}",
                variableMapping: "",
                errorHandling: "",
                successPath: "",
                failurePath: "",
                notes: "Ends general inquiry flow.",
                position: { x: 600, y: 110 },
                nextNodeId: null
            }
        ],
        validation: {
            missingConnections: 0,
            orphanNodes: 0,
            duplicateNodeNames: 0,
            unreachablePaths: 0,
            missingEndNodes: 0,
            invalidConfigurations: 0
        },
        analytics: {
            totalExecutions: 1112,
            successRate: 93,
            humanHandoverRate: 7,
            averageCompletionTime: "2m 20s",
            dropOffRate: 5,
            mostClickedButtons: ["General Info", "Contact Us"]
        },
        versions: [
            { version: 2.9, updatedAt: "Today, 14:10", note: "Updated contact flow" },
            { version: 2.8, updatedAt: "Jul 22, 2026", note: "Added feedback option" }
        ],
        recentActivity: [
            { id: 1, title: "Published new inquiry flow", time: "45 min ago" },
            { id: 2, title: "Improved customer support wording", time: "1 day ago" }
        ],
        preview: {
            title: "General Inquiry",
            messages: [
                { type: "bot", text: "How may I assist you with your inquiry today?" },
                { type: "user", text: "Contact desk" },
                { type: "bot", text: "We will connect you with reception" }
            ]
        }
    }
];

export const flowStats = [
    { label: "Total Flows", value: "24", icon: "AutoAwesomeMotion" },
    { label: "Published Flows", value: "14", icon: "RocketLaunch" },
    { label: "Draft Flows", value: "8", icon: "Drafts" },
    { label: "Active Hospitals", value: "21", icon: "Business" }
];
